[package]
name = "ims"
version = "0.1.0"
authors = ["Sean.W <imseean@gmail.com>"]

[dependencies]
clap = "2.29.2"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "0.5", features = ["serde","v4"] }
